#!/bin/bash

set -e
cp results/twentytwenty/hello-world.html twentytwenty-hello-world.html
cp results/twentytwenty/monster.html twentytwenty-monster.html

echo "<!-- 🚫🚫🚫 DO NOT EDIT THIS FILE DIRECTLY. It is generated with ./generate-readme.md -->" > ./README.md
echo "# AMP WordPress Theme Compatibility" >> ./README.md
echo 'What follows are the fidings of WordPress.org theme compatibility with the [official AMP plugin](https://github.com/ampproject/amp-wp).' >> ./README.md
echo '' >> ./README.md

echo '## CSS `amp-custom` Usage' >> ./README.md
echo 'The following two sections gather data on how much CSS is present on AMP pages when the [most popular themes on WordPress.org](https://wordpress.org/themes/browse/popular/) are active. The “Original CSS” column indicates the total amount of CSS (in bytes) being loaded onto the page, and the “Minified CSS” column indicates the amount after the original CSS is minified through removal of comments, whitespace, and unused selectors/rules via tree-shaking.' >> ./README.md
echo '' >> ./README.md

echo "### Light Page" >> ./README.md
echo "The following lists the CSS output by the most popular WordPress themes when rendering the default Hello World post. The less HTML there is on a page, the more effective the AMP plugin's CSS tree shaker is able to remove style rules. See [AMP page](twentytwenty-hello-world.html) from the Twenty Twenty theme (132KB)." >> ./README.md
echo '' >> ./README.md
lando wp --quiet gather-stats hello-world >> ./README.md
echo '' >> ./README.md

echo "### Heavy Page" >> ./README.md
echo "The following lists the CSS output by the most popular WordPress themes when rendering a page which is fully loaded with all content from the [theme unit test data](https://codex.wordpress.org/Theme_Unit_Test) as well as populating all sidebars and all nav menus. When there is a lot of varied HTML there a page, the AMP plugin's CSS tree shaker less effective at removing style rules. See [AMP page](twentytwenty-hello-world.html) from the Twenty Twenty theme (676KB)." >> ./README.md
echo '' >> ./README.md
lando wp --quiet gather-stats monster >> ./README.md
